name: release

on:
  push:
    tags:
      - "*"
jobs:
  release:
    strategy:
      matrix:
        go-version:
          - 1.15.x
        goos:
          - linux
        goarch:
          - amd64
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o deploy-helper -ldflags '-X deploy-helper/cmd.version=${{ steps.tag_name.outputs.SOURCE_TAG }} -X deploy-helper/cmd.githash=${{ github.sha }}'
          tar -zcvf deploy-helper_${{ steps.tag_name.outputs.SOURCE_TAG }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz deploy-helper
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./deploy-helper_${{ steps.tag_name.outputs.SOURCE_TAG }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
